clMathLibraries/clBLAS

- src/FindOpenCL.cmake
OpenCL is not found on Ubuntu 14.04 with a default CUDA install. I added a few path hints that should solve this problem.
> fixed FindOpenCL.cmake file to find OpenCL on Ubuntu 14.04 with CUDA 6.0

- src/library/blas/gens/gemm.c
- Fixes issues with on intel SDKs on Windows, Apple SDKs on OSX
- Fixes #62
> Always cast get_*_* to uints before casting to vectors.

- .travis.yml
- src/CMakeLists.txt
as documented, this option mainly make sense on windows. On unixes, it is
quite certainly not the expected behavior.
> use the default install prefix on unixes

- src/CMakeLists.txt
- src/clBLASConfig.cmake.in
- src/clBLASConfigVersion.cmake.in
- src/library/CMakeLists.txt
so clBLAS can be used in a cmake project with the usual find_package command
find_package(clBLAS REQUIRED)
include_directories(${CLBLAS_INCLUDE_DIRS})
tarkget_link_libraries(mytarget ${CLBLAS_LIBRARIES})
> install clBLAS cmake configuration and version file

- src/library/blas/functor/hawaii.cc
- src/library/blas/functor/hawaii_sgemmBranchKernel.cc
- src/library/blas/gens/clTemplates/sgemm_gcn_SmallMatrices.cl
- src/library/blas/gens/clTemplates/sgemm_hawaiiSplitKernel.cl
improve big sgemm column NN perf: replace barrier() with mem_fence() in the inner loop. 
improve small sgemm NN perf: for small sgemm (M*N < 900*900) and M or N is not multiples of 32, use kernel with micro tile size 2 by 2 instead of micro tile size 6 by 6. 
Note: kernel with other micro tile sizes might have better performance than these 2 cases. Finer tuned heuristic of switching from kernel to kernel is also a good to have.
> improve big sgemm column NN perf. improve small sgemm NN perf.

- src/samples/CMakeLists.txt
At the moment the compiled samples get installed to `/usr/bin` and the source gets installed to `/usr/samples`. Fixed with this commit.
> Fix install location of samples

- src/scripts/perf/CMakeLists.txt
Python scripts should not get installed to `/usr/bin`. Same as for clFFT https://github.com/clMathLibraries/clFFT/pull/52.
> Install scripts/perf to share/clBLAS on non WIN32 systems

- src/CMakeLists.txt
[C.f #92] changed the CMakeLists.txt file BUILD_TEST block to increase readability, fix broken build on OSX systems.
refactored CMakeLists.txt in BUILD_TEST block
added test for OSX detection to turn off CORR_TEST_WITH_ACML
fyi: CMake generates a makefile which builds fine on my OSX machine.
> added test for OSX detection to turn

- src/CMakeLists.txt
The cmake configuration should go to /usr/lib{64}/cmake/clBLAS and not to /usr/share/clBLAS. Similar to https://github.com/clMathLibraries/clFFT/pull/88.
> Install cmake configuration to lib/cmake/clBLAS

- src/FindOpenCL.cmake
> add x86_64/sdk suffix as search location for libOpenCL.so

- src/scripts/perf/blasPerformanceTesting.py
due to the changes made in PR #72
> python scripts should call clBLAS-client instead of client

- src/library/blas/ixamax.c
- src/library/blas/xasum.c
- src/library/blas/xaxpy.c
- src/library/blas/xcopy.c
- src/library/blas/xdot.c
- src/library/blas/xger.c
- src/library/blas/xher.c
- src/library/blas/xher2.c
- src/library/blas/xrot.c
- src/library/blas/xrotg.c
- src/library/blas/xrotm.c
- src/library/blas/xrotmg.c
- src/library/blas/xscal.c
- src/library/blas/xswap.c
- src/library/blas/xsymm.c
- src/library/blas/xsyr.c
- src/library/blas/xsyr2.c
- src/library/blas/xtbmv.c
- src/library/blas/xtrmv.c
Three changes related to error-checking were made:
- The order of error-checking of the 3 matrices A, B, C for the SYMM routine was changed to match the order of other level-3 routines. Before: first check B, then C, then A. Now: first check A, then B, then C. This is consistent with other level-3 routines such as GEMM.
- Removal of debug `printf`-statements for the SYMM routine. Earlier, before an error-code was returned, a message was printed to screen. It is better to give control back to the caller of the function: the error-code contains the information that was printed. The `printf`'s are removed entirely to match the other level-3 routines.
- A good portion of the level-1 and level-2 routines contained similar `printf`-statements when an error-code was returned. They are now …
> SYMM error-check order and removal of debug printf statements

- src/library/blas/generic/common.c
When computing the requirement of an OpenCL buffer in the case of a matrix, there is a check for a corner case, described in `blas/generic/common.c` as:
> It is possible to allocate a buffer, and set up lda & ldb such that it looks like it will access outside of the allocated buffer, but if M & N are kept small enough, no out of bounds access will occur.  Compensate for the offset values and the unused tail memory caused by lda & ldb.
I don't doubt this corner-case, however, I am having trouble with the regular scenario, as the memory used is then set to zero:
```
if (( offA + matrSize ) > unusedTail) {
memUsed = offA + matrSize - unusedTail;
} else {
memUsed = 0; // Shouldn't this be "offA + matrSize"?
}
```
I applied a 'fix' in two cases, one for regular matrices and one for banded …
> Updated the computation of matrix memory requirements

- src/library/CMakeLists.txt
- src/library/bingen.cmake
- src/library/blas/functor/hawaii.cc
- src/library/blas/functor/hawaii_sgemmBig1024Kernel.cc
- src/library/blas/functor/hawaii_sgemmSplitKernel.cc
- src/library/blas/functor/include/hawaii_sgemmBig1024Kernel.h
- src/library/blas/gens/clTemplates/sgemm_gcn_bigMatrices.cl
- src/library/blas/xgemm.cc
This PR is an attempt to fix the performance drop of SGEMM column major NT or row major TN when lda and ldb are big multiples of 1024 such as 4096, 5120, 6144, 7168, 8192 and so forth.
The performance drop at those sizes are likely caused by cache trashing that multiple CUs are trying to read from the same global memory channel. The easiest way to fix this problem is to pad the input data by lda and ldb (such as lda = 4097, ldb = 4097). However, an OpenCL level library does not have the control over how users allocate the host memory. In this regard, it is worthwhile to try to fix this problem from within the library.
At size 4096 and 5120 we choose to use kernels with macro tile size of 128 instead of 96. Doing this effectively reduces the number of work groups and thus reduces the …
> fix the performance drop of SGEMM column major NT or row major TN when lda and ldb are big multiples of 1024 such as 4096, 5120, 6144, 7168, 8192

- src/library/blas/functor/functor.cc
- src/library/blas/generic/binary_lookup.cc
Similar to the bug reported in `clFFT`. Some missing inclusion of `stdlib.h` prevent compilation on most architectures but `amd64`.
> add missing includes on stdlib

- src/library/blas/generic/binary_lookup.cc
seq and getStorageMode are defined in both clBLAS and clFFT. This causes redefinition warnings when using both in the same project.
Opened PR in https://github.com/clMathLibraries/clFFT/pull/103
> Fix redefinition warnings when using with clFFT

- src/library/blas/xtrsm.cc
The stdlib include is required for calloc / free. Fixes an FTBFS error on Debian.
> add missing include on stdlib.h

- src/CMakeLists.txt
The following sets up either the "-m32" or "-m64" compiler flag depending on the pointer size:
```
set(CMAKE_C_FLAGS "-m${TARGET_PLATFORM} ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-m${TARGET_PLATFORM} ${CMAKE_CXX_FLAGS}")
set(CMAKE_Fortran_FLAGS "-m${TARGET_PLATFORM} ${CMAKE_Fortran_FLAGS}")
```
Unfortunately, this appears to be x86 specific. 
For example, my local GNU compiler for ARM does not support it:
```
$ gcc --version
gcc (Gentoo 5.3.0 p1.0, pie-0.6.5) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ gcc -dumpmachine
armv7a-hardfloat-linux-gnueabi
$ gcc -m32
gcc: error: unrecognized command line option '-m32'
```
That's why …
> Only use the "-m32" or "-m64" compiler flags on x86.

- .travis.yml
- appveyor.yml
OpenCL headers were moved to Github (https://github.com/KhronosGroup/OpenCL-Headers/) and are no longer available at https://www.khronos.org/registry/cl/api/.
> Update .travis.yml and appveyor.yml

- src/tests/correctness/blas-lapack.c
In clblas' "blas-lapack.c" , "cdotu" call "cdotusub_" in linux branch. 
Yet, in fact, it is unnecessary since there is a "cdotu" routine implementation in BLAS. 
Similar reason applies on cdotu, zdotu,zdotc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/242)
> fix the compilation bug about c(z)dotc_ in issue #142 and issue #184.

- src/tests/common.cpp
- src/tests/include/common.h
- src/tests/include/matrix.h
old gtest code was using float == float and double == double, new code uses GTEST_FLOAT_EQ(a,b) and GTEST_DOUBLE_EQ(a,b) which compares to whithin 4ulps. Better written code also reduces a lot of duplicate code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/245)
> fixed compareMatrices to use GTEST_FLOAT_EQ

- src/library/blas/xgemm.cc
kernelname missing, so if you build with AUTOGEMM_PRINT_DEBUG defined, there is a build error at line 274 of xgemm.cc.  This PR fixes this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/249)
> fix error with missing KernelName variable

- README.md
- src/CMakeLists.txt
- src/FindNetlib.cmake
- src/client/CMakeLists.txt
- src/client/clfunc_common.hpp
- src/client/clfunc_xgemm.hpp
- src/client/clfunc_xtrmm.hpp
- src/client/client.cpp
Although we have tested and seen green lights on extensive platforms including mainstream CPUs & GPUs on windows/linux, we still keep seeing users reporting failures on particular processors & environment.  Many of them are beyond our resources.  clBLAS team is a very small group.  So we always encourage users to debug their failures.  Except the **gtest framework** already integrated in clBLAS which hard coded various configurations  (by configurations, I mean, matrix size, transpose option, etc),  we have actually provided the **"client"** tool to test the BLAS routines' performance.  
Users can specify whatever configurations through command lines. 
One thing was missing that users can not verify/validate the correctness through client. 
So, starting from today, users can easily do it …
> allow users to easily verify the gemm/trmm GPU results with the netlib cblas through client

- src/CMakeLists.txt
clang with ```-std=c++11``` fails to compile the project because there are narrowing conversions in ```src/library/blas/xtrsm.cc``` and a bunch of other files. The problem is reproducible for me if instead of
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-narrowing")
I set
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
Disabling the error seems like the easiest solution. Another alternative is to add explicit casts, but it touched multiple places in the code so I figured that this is the safer path.
Also, having an explicit section with compile options for clang may save some confusion - I spent quite a bit of time wondering why my CXXFLAGS are not respected until I realized that clang is not considered a GNUCXX compiler so the first ```if``` does not apply to it.
---
This change is …
> Disable clang error on narrowing conversions.

- CONTRIBUTING.md
As discussed in https://github.com/clMathLibraries/clBLAS/pull/280 - creating a new PR against the develop branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/282)
> Point the CONTRIBUTING wiki links to the correct repository

- src/library/blas/gens/clTemplates/her2.cl
- src/library/blas/gens/clTemplates/syr2.cl
- src/library/blas/gens/clTemplates/syr2_her2.cl
- src/library/blas/gens/iamax.cpp
Two bug fixes:
1) ixamax crashes if x offset is not a multiple of vector size. Caused by checking offa, when it should check offb, to determine whether to use vload.
2) syr2/her2 get wrong result when incx != incy. Caused by Y using incx instead of incy.
> ixamax and syr2/her2 bugs

- src/library/blas/generic/common.c
- src/library/blas/generic/solution_seq.c
- src/library/blas/ixamax.c
- src/library/blas/xasum.c
- src/library/blas/xdot.c
- src/library/blas/xhemv.c
- src/library/blas/xher2k.c
- src/library/blas/xhpmv.c
- src/library/blas/xnrm2.c
- src/library/blas/xspmv.c
- src/library/blas/xtrsv.c
Many L2 & L1 routines, which used multiple kernels to compute result
leaked internal cl_events.
Removed '-g' clBuildProgram option from library debug builds.  This
flag causes an internal compiler error for debug builds in xTRMM.  The
flag is not very useful and has caused too many problems.
> Fixing internal library cl_event leaks

- src/tests/performance/test-performance.cpp
setDeviceType only takes one argument: params. This was causing build errors.
> Fix call to setDeviceType in test-performance.cpp

- src/samples/example_ctrsm.c
.s is more portable, and .x does not work with -std=c99 which
does not have anonymous structs.
Fix #307.
> Use .s[0] instead of .x in example_ctrsm.c
