clMathLibraries/clBLAS

- src/CMakeLists.txt
> don't install in lib64 on mac

- .travis.yml
- src/client/CMakeLists.txt
- src/library/tools/tune/CMakeLists.txt
in order to avoid conflict with other projects
> add clBLAS- prefix to the client and tune executable

- .travis.yml
- src/CMakeLists.txt
- src/FindOpenCL.cmake
- src/clBLASConfig.cmake.in
- src/clBLASConfigVersion.cmake.in
- src/client/CMakeLists.txt
- src/include/granulation.h
- src/library/CMakeLists.txt
- src/library/blas/generic/common.c
- src/library/blas/gens/blas_kgen.h
- src/library/blas/gens/fetch.c
- src/library/blas/gens/gemm.c
- src/library/blas/gens/syrxk.c
- src/library/blas/gens/tilemul.c
- src/library/blas/include/blas_funcs.h
- src/library/blas/xgemm.c
- src/library/tools/ktest/naive/naive_blas.cpp
- src/library/tools/tune/CMakeLists.txt
- src/library/tools/tune/subdim.c
- src/tests/CMakeLists.txt
- src/tests/copyTestDependencies.cmake.in
- src/tests/correctness/tcase-filter.cpp
- src/tests/correctness/test-correctness.cpp
- src/tests/gtest.cmake
> merge develop branch into master branch

- .travis.yml
- src/library/blas/functor/functor_selector.cc
download OpenCL 1.2 header files from Khronos directly.
> fix travis CI build

- src/library/blas/functor/hawaii.cc
- src/library/blas/functor/hawaii_sgemmBranchKernel.cc
- src/library/blas/gens/clTemplates/sgemm_gcn_SmallMatrices.cl
- src/library/blas/gens/clTemplates/sgemm_hawaiiSplitKernel.cl
> improve small sgemm column major TN on Hawaii

- src/samples/CMakeLists.txt
if-else statement inside install() does not seem to work.
> fix cmake bug introduced by pull request #75

- src/CMakeLists.txt
Reverts clMathLibraries/clBLAS#97
> Revert "Fix to enable successful build on MacOSX "

- src/library/CMakeLists.txt
- src/library/bingen.cmake
- src/library/blas/functor/bonaire.cc
- src/library/blas/functor/gcn_zgemm.cc
- src/library/blas/functor/hawaii.cc
- src/library/blas/functor/include/gcn_zgemm.h
- src/library/blas/functor/include/hawaii.h
- src/library/blas/gens/clTemplates/zgemm_gcn.cl
added gcn_zgemm.cc .h and zgemm.cl to add zgemm support.
modified hawaii.cc .h to incorporate zgemm support
modified make files for zgemm support
> adding zgemm kernel for hawaii

- .travis.yml
- README.md
- appveyor.yml
- src/library/blas/AutoGemm/AutoGemmTools/ProfileAutoGemm.cpp
- src/library/blas/AutoGemm/Includes.py
- src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.h
Adding support for visual studio on appveyor 
Adding support for clang on Macosx on travis
Updating Linux travis yaml file
Also, a few fixes to build for clang on MacOSX
> Improvements to CI systems

- src/library/blas/gens/clTemplates/ger.cl
See https://github.com/clMathLibraries/clBLAS/issues/108 for more details
> Fix kernel crash on nvidia, caused by float4 alignemtn error

- .travis.yml
- src/CMakeLists.txt
- src/FindNetlib.cmake
> find libblas.so correctly. use libblas.so for testing by default instead of libacml.so

- src/library/blas/trtri/diag_dtrtri_lower_128_16.cpp
- src/library/blas/trtri/diag_dtrtri_upper_128_16.cpp
- src/library/blas/trtri/diag_dtrtri_upper_192_12.cpp
error: embedding a #pragma directive within
macro arguments is not supported
> Fixed clang build error

- src/library/blas/AutoGemm/AutoGemm.py
- src/library/blas/AutoGemm/AutoGemmParameters.py
- src/library/blas/AutoGemm/Includes.py
- src/library/blas/AutoGemm/KernelOpenCL.py
- src/library/blas/AutoGemm/KernelParameters.py
- src/library/blas/AutoGemm/KernelSelection.py
- src/library/blas/AutoGemm/KernelsToPreCompile.py
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NN_B0_MX048_NX048_KX08_src.cpp
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NN_B1_MX048_NX048_KX08_src.cpp
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NT_B0_MX048_NX048_KX08_src.cpp
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NT_B1_MX048_NX048_KX08_src.cpp
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_TN_B0_MX048_NX048_KX08_src.cpp
- src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_TN_B1_MX048_NX048_KX08_src.cpp
- src/library/blas/xgemm.cc
- src/library/blas/xtrsm.cc
- Fixes #197 
- Also fixes missing `cl_khr_fp64`  failures on some devices.
> Fixing errors when using multiple contexts

- src/library/CMakeLists.txt
> Find the python interpreter using cmake

- src/library/blas/AutoGemm/KernelOpenCL.py
- src/library/blas/AutoGemm/KernelParameters.py
- src/library/blas/trtri/TrtriKernelSourceIncludes.h
- Fixes #201 
- Fixes #203 
- Fixes kernel compilation issues of `trtri` on Intel platform.
> Fixing issue with beta == 0 in AutoGemm kernels

- .travis.yml
use the pull request to test if travis ci is fixed since my fork's travis ci is still pointing to an deleted fork.
> attempts to fix travis ci build with missing fglrx

- src/library/blas/xgemm.cc
each thread will have its own kernel map and, therefore, its own set of kernels
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/235)
> proposed fix for gemm thread safety; using thread-local storage

- src/tests/correctness/blas-lapack.h
There is a bug in last pull request. The header should be updated, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/244)
> fix the header accordingly following last PR

- .gitignore
Add .pyc files to .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/254)
> Add .pyc files to .gitignore

- src/library/CMakeLists.txt
Make installing source tree optional
Addresses https://github.com/clMathLibraries/clBLAS/issues/248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/252)
> Make installing source tree optional

- src/clBLAS.h
- src/include/kerngen.h
- src/library/blas/generic/solution_seq_make.c
- src/library/blas/gens/clTemplates/gemm.cl
- src/library/blas/gens/clTemplates/symm.cl
- src/library/blas/gens/clTemplates/trmv.cl
- src/library/blas/gens/kprintf.cpp
- src/library/blas/gens/trsv_gemv.cpp
- src/library/blas/include/kprintf.hpp
- src/library/blas/xtrsv.c
- src/library/common/kerngen_core.c
looks trivial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/276)
> fix #265 - spelling errors in comments and print statements

- src/CMakeLists.txt
- src/library/CMakeLists.txt
New PR from https://github.com/clMathLibraries/clBLAS/pull/278 where I hadn't documented myself on how to contribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/clmathlibraries/clblas/283)
> add missing dependency to pthread (using rwlock functions)

- appveyor.yml
- src/CMakeLists.txt
- src/client/client.cpp
Adding netlib as a dependency for the client on linux based
systems.
> Removing ACML as a build dependency for tests

- src/library/blas/AutoGemm/KernelOpenCL.py
- src/library/blas/gens/clTemplates/dot.cl
- src/library/blas/gens/clTemplates/gbmv.cl
- src/library/blas/gens/clTemplates/her2.cl
- src/library/blas/gens/clTemplates/iamax.cl
- src/library/blas/gens/clTemplates/reduction.cl
- src/library/blas/gens/clTemplates/rotg.cl
- src/library/blas/gens/clTemplates/rotm.cl
- src/library/blas/gens/clTemplates/rotmg.cl
- src/library/blas/gens/clTemplates/syr_her.cl
- src/library/blas/gens/clTemplates/trsv.cl
- src/library/blas/gens/clTemplates/trsv_gemv.cl
- src/library/blas/gens/trsm.c
- src/library/blas/xgemm.cc
This is a set of patches that fix kernel compatibility issues with a number of devices of other platforms (chiefly NVIDIA and Intel), ranging from inability to compile to actual runtime crashes.
> Portability fixes

- src/library/CMakeLists.txt
This avoids problem when using `add_subdirectory`.
> Remove usage of CMAKE_SOURCE_DIR
